movie/urls.py
from django.urls import path

from. import views


app_name ='movie'

urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:id>/',views.detail,name="detail"),
    path('add-movie/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete'),
]

movie_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movie.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movie/models.py
from django.db import models


class Movie(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    year = models.IntegerField()
    image = models.ImageField(upload_to='images/',blank=True,null=True)

    def __str__(self):
        return self.name

movie/forms.py
from django import forms

from.models import Movie


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ('name', 'description', 'year', 'image',)

movie/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render

from movie.forms import MovieForm

from.models import Movie


def index(request):

    instances = Movie.objects.all()

    context = {
        'instances': instances,
    }  

    return render(request, 'index.html', context)


def detail(request, id):
    instance = Movie.objects.get(id=id)
    context = {
        'instance': instance,
    }

    return render(request, 'detail.html',context)


def add_movie(request):
    if request.method=='POST':
        name = request.POST.get('name')
        description = request.POST.get('description')
        year = request.POST.get('year')
        image = request.FILES.get('image')

        movie = Movie(name=name, description=description, year=year, image=image)
        movie.save()

    return render(request, 'add.html')


def update(request, id):
    movie = Movie.objects.get(id=id)
    form = MovieForm(request.POST or None, request.FILES or None, instance=movie)

    if form.is_valid():
        form.save()
        return redirect('/')
    
    context = {
        'form': form,
       'movie': movie,
    }
    
    return render(request, 'update.html', context=context)


def delete(request, id):
    if request.method == 'POST':
        movie = Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    
    return render(request, 'delete.html')

templates/add.html
{% extends 'base.html' %}

{% block content %}
<div class="container col-md-2">
    <form method="post" class="add-form" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="text" id="name" name="name" placeholder="Enter Movie name">

        <input type="text" id="description" name="description" placeholder="Enter Movie description">

        <label for="image">Add movie image</label>
        <input type="file" id="image" name="image" placeholder="Add Movie image">

        <input type="number" id="year" name="year" placeholder="Enter a year">

        <input type="submit">
    </form>

</div>
   
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'movie:index' %}">Movie Site</a>
        <a href="{% url 'movie:add_movie' %}" class="btn btn-success">Add Movie</a>
    </nav>

    {% block content %}
    {% endblock %}
</body>
</html>

templates/delete.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        Are you want to delete?
        {{ form }}
        <input type="submit" class="btn btn-danger">
    </form>
{% endblock %}

templates/detail.html
{% extends 'base.html' %}

{% block content %} 
<div class="container">
    <div class="row">
        <div class="col-md-3 mr-6 detail-image mr-6">
            <img src="{{instance.image.url}}" width="300px" height="300px" alt="">
        </div>
        <div class="col-md-6 mt-5 ml-5">
            <h1>{{ instance.name }}</h1>
            <p>{{instance.description}}</p>
            <p>{{instance.year}}</p>
            <a href="{% url 'movie:update' instance.id %}" class="btn btn-success">Edit</a>
            <a href="{% url 'movie:delete' instance.id %}" class="btn btn-danger">Delete</a>
        </div>
    </div>
</div>
{% endblock %}
                                                       

templates/index.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-5">
    <div class="row">
        {% for movies in instances %}
        <div class="col-md-3 mr-3">
            <div class="card" style="width: 18rem;height: 31rem;margin-bottom: 20px; ">
                <img class="card-img-top movie_image" src="{{movies.image.url}}" alt="Card image cap">
                <div class="card-body">
                  <h5 class="card-title">{{ movies.name }}</h5>
                  <p class="card-text">{{ movies.description }} </p>
                  <a href="{% url 'movie:detail' movies.id %}" class="btn btn-primary">View</a>
                </div>
              </div>
        </div>
        {% endfor %}
    </div>
</div>
   
{% endblock %}

templates/update.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="POST" enctype="multipart/form-data" class="update">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" style="background-color: green;">
</form>
{% endblock %}